### PR TITLE
Initial release

### PR DESCRIPTION
**Pull request by twolfson**
This is the initial build out of `fixed-server`. In this PR:
- Added `FixedServer` and `FixedServerFactory`
- Added tests

/cc @mlmorg

### CODE REVIEW

**Comment by mlmorg** [comment]
:+1: Looks great

**Comment by mlmorg** [comment]
May want to say something about this being for mocha testing...

**Comment by Raynos** [comment]
README doesn't mention it relies on the global `before` and `after` that only exist in mocha if run under `bdd` interface. Probably worth a comment.

**Comment by twolfson** [comment]
The `.run` method is in there and technically it is open enough to be used sans `mocha`.

**Comment by twolfson** [comment]
`before` and `after` run in all cases with `mocha`, even the `tdd` interface. They are aliases.

**Comment by Raynos** [comment]
didn't know that `before` and `after` exist in all interfaces. interesting.

**Comment by twolfson** [comment]
Yep, here is proof:

https://github.com/visionmedia/mocha/blob/1.16.2/lib/interfaces/bdd.js#L36-L38

https://github.com/visionmedia/mocha/blob/1.16.2/lib/interfaces/tdd.js#L60-L62

**Pull request merged**
